---
title: "Kenneth Blake Vernon"
params:
  appointments: TRUE
  education: TRUE
  publications: TRUE
  funding: TRUE
  teaching: TRUE
  students: FALSE
  presentations: TRUE 
  affiliations: TRUE
  synergy: TRUE
  committees: FALSE
  development: FALSE
  fieldwork: FALSE
output: 
  pagedown::html_paged:
    self_contained: TRUE
    css: style.css
    number_sections: FALSE
knit: 
  pagedown::chrome_print:
    async: TRUE
---

```{r setup, include = FALSE}

### LIBRARIES ###
library(dplyr)
library(glue)
library(googlesheets4)
library(here)
library(icons)
library(kableExtra)
library(knitr)
library(RefManageR)
library(stringr)
library(tidyr)

### SETTINGS ###
knitr::opts_chunk$set(
  echo = FALSE, 
  warning = FALSE, 
  message = FALSE,
  results = "asis"
)

options(knitr.kable.NA = "")

### HELPER FUNCTIONS ###
fa <- icons::fontawesome 
ai <- icons::academicons

source(here("cv_blocks.R"))

### CREDENTIALS ###
load(here("credentials.RData"))

### BIBLIOGRAPHY ###
bib <- cv_get_bibliography(zotero, collection)

```

::: {#disclaimer} 
CV last updated on `r Sys.Date()` 
:::

:::::: {#profile}

::: {#address}
Department of Anthropology  
University of Utah  
260 Central Campus Drive  
Salt Lake City, UT 84112  
(801) 581-6252  
[faculty.utah.edu/~kbvernon](https://faculty.utah.edu/~kbvernon)
:::

::: {#social}
[kbvernon](https://github.com/kbvernon)  `r fa("github")`  
[0000-0003-0098-5092](https://orcid.org/0000-0003-0098-5092) `r ai("orcid")`  
[2PE4za4AAAAJ](https://scholar.google.com/citations?user=2PE4za4AAAAJ&hl=en) `r ai("google-scholar")`  
:::

::::::

:::::: {#main}

```{r, child = if(params$appointments) here("content/appointments.Rmd")}
```

```{r, child = if(params$education) here("content/education.Rmd")}
```

```{r, child = if(params$publications) here("content/publications.Rmd")}
```

```{r, child = if(params$funding) here("content/funding.Rmd")}
```

```{r, child = if(params$teaching) here("content/teaching.Rmd")}
```

```{r, child = if(params$students) here("content/_students.Rmd")}
```

```{r, child = if(params$presentations) here("content/presentations.Rmd")}
```

```{r, child = if(params$affiliations) here("content/affiliations.Rmd")}
```

```{r, child = if(params$synergy) here("content/synergy.Rmd")}
```

```{r, child = if(params$committees) here("content/committees.Rmd")}
```

```{r, child = if(params$development) here("content/development.Rmd")}
```

```{r, child = if(params$fieldwork) here("content/fieldwork.Rmd")}
```

## `r fa("envelope")` References

_Available upon request._

::::::